### ISSUE TITLE
Questions about deform

### ISSUE THREAD

**Issue by FANzhaoxin666** [JeremyWANGJZ/Category-6D-Pose#1]
Hi！
 I have read you paper and the code of SPD. I find there may be some mistake in your paper.  When computing the reconstuction loss,  you mean the you compute CD between  gt NOCS and reconstructed NOCS. However, I found that prior+deform=model， the model is the extract 3D CAD model of the object in the training dataset.  Another evidence is that in the evaluation code, the author of SPD directly uses the length, width and height of prior + deform as the size of the object. Obviously, if prior + deform is NOCs, this calculation cannot be established (because NOCS can only be taken as 0-1). 
 Hope my observation can help you.

**Comment by SocialGoodAI** [comment]
Hi Zhaoxin,

Prior+deform= model is under the NOCS space,  thus our description that we compute CD between gt NOCS and reconstructed NOCS model is OK. Thanks for your kind suggestions.
