### ISSUE TITLE
CR-Net 和SGPA中SPD*的数据不一致，CR-Net和SGPA是在相同机器上的对比结果吗？

### ISSUE THREAD

**Issue by Bingo-1996** [JeremyWANGJZ/Category-6D-Pose#3]
同学您好！最近看到了您课题组内两篇有关category-level pose estimation的同期工作，
[1] Category-Level 6D Object Pose Estimation via Cascaded Relation and Recurrent Reconstruction Networks. IROS 2021.
[2] SGPA: Structure-Guided Prior Adaptation for Category-Level 6D Object Pose Estimation. ICCV2021.

但是有个问题令我感觉十分困惑：这两篇论文都对baseline方法: SPD进行了重新训练, 但是两篇论文中报告的重新训练结果却不一致（如下图，CAMERA数据集：ICCV中SDP*都比IROS中报告的更高，而REAL数据集却是IROS中报告的结果比ICCV的高），请问这是因为IROS论文和ICCV论文用了不同的GPU来重新训练SPD吗？
这样的话，CR-Net和SGPA是否也是在不同的机器上训练的呢？

![Screenshot from 2021-10-14 12-22-38](https://user-images.githubusercontent.com/69563953/137251672-39bde518-a1ea-45b7-9d3a-fde6d761278d.png)

**Comment by SocialGoodAI** [comment]
Hi Bingo, 

The SPD results report in CRNet are trained under the same setting with CRNet, and SPD results report in SGPA are trained under the same setting with SGPA for a fair comparison. Thus the batch size, training iterations, and epochs are different, which causes the problem. You can refer to our codes and papers for detailed settings.
