### ISSUE TITLE
关于重新训练的实验结果

### ISSUE THREAD

**Issue by touchthefish233** [JeremyWANGJZ/Category-6D-Pose#4]
同学你好，这个工作看起来非常的棒，在实现的时候遇到了个问题，在Camera数据集上重新训练，在验证集上的表现和论文中给出的结果不一致，可以帮忙指出复现过程中出现的问题吗，在第三轮训练的时候5cm5度的精度为42.575216，一直训练到第六轮都没有变化
![image](https://user-images.githubusercontent.com/68363637/165928780-fbfefb9e-b501-47c6-8fdb-7a4888389efe.png)

**Comment by SocialGoodAI** [comment]
Hello, we use the transformer for relation modeling, thus it cost more time to train the codes. As we point out in the paper, we train our networks for 50 epochs in total, and there are 4K iterations in each epoch.

You may also refer to our ICCV2021 paper SGPA: https://github.com/leo94-hk/SGPA, which only needs 15 epochs to converge.

**Comment by touchthefish233** [comment]
非常感谢
